name: frontend_app
description: A Travel & Tourism App

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #  User Interface Components
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1

  #  Network and API Handling
  dio: ^5.3.3
  url_launcher: ^6.1.14

  #  State Management
  get: ^4.6.6

  #  Localization and Internationalization
  intl: ^0.18.1

  #  Security and Data Storage
  flutter_secure_storage: ^9.0.0

  #  Configuration Management
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

