# Generated by Django 4.2.6 on 2023-10-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_propertyimage_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='number_of_queen_bedrooms',
            new_name='number_of_guest_allowed',
        ),
    ]
