# Generated by Django 4.2.6 on 2023-10-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_number_of_beds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='number_of_beds',
            new_name='number_of_bedrooms',
        ),
    ]
