# Generated by Django 4.2.6 on 2023-10-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_number_of_beds_property_number_of_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
